export const jsTypes = {
  array: "Array",
  bigint: "number",
  bigserial: "number",
  bit: "string",
  "bit varying": "string",
  boolean: "boolean",
  box: "string",
  bytea: "string",
  character: "string",
  "character varying": "string",
  cidr: "string",
  circle: "string",
  citext: "string",
  date: "Date",
  "double precision": "number",
  hstore: "Object",
  inet: "string",
  integer: "number",
  interval: "string",
  json: "Object",
  jsonb: "Object",
  line: "string",
  lseg: "string",
  macaddr: "string",
  money: "number",
  numeric: "number",
  path: "string",
  point: "string",
  polygon: "string",
  real: "number",
  smallint: "number",
  smallserial: "number",
  serial: "number",
  text: "string",
  "time without time zone": "string",
  "time with time zone": "string",
  "timestamp without time zone": "Date",
  "timestamp with time zone": "Date",
  tsquery: "string",
  tsvector: "string",
  txid_snapshot: "string",
  uuid: "string",
  xml: "string",
  varchar: "string",
  "user-defined": "string",
  int4range: "string",
  int8range: "string",
  numrange: "string",
  tsrange: "string",
  tstzrange: "string",
  daterange: "string",
};
